const C=window.LLA_CURRICULUM;let currentSubject=null,currentLesson=null,hiddenMemory=false,remembered=new Set();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function speak(text,voice="girl",lang="en"){if(!("speechSynthesis"in window))return;const u=new SpeechSynthesisUtterance(text.replace(/[^A-Za-z0-9,.!? ]/g," ").replace(/\s+/g," ").trim());u.lang=lang==="ar"?"ar-QA":"en-GB";u.rate=.72;u.pitch=voice==="girl"?1.18:1.02;speechSynthesis.cancel();speechSynthesis.speak(u)}
function renderSubjects(){const box=$("#subjects");box.innerHTML=C.subjects.map(s=>`<button class="subject" data-id="${s.id}"><span class="icon">${s.icon}</span><b>${s.title}</b><span class="ar">${s.ar}</span><small>${s.lessons.length} learning adventures</small></button>`).join("");box.querySelectorAll(".subject").forEach(b=>b.onclick=()=>openSubject(b.dataset.id));const q=$("#qatarCore");q.innerHTML=C.qatarCore.map(x=>`<div class="subject locked"><span class="icon">${x.icon}</span><b>${x.title}</b><span class="ar">${x.ar}</span><small>Specialist review before release • مراجعة متخصصة</small></div>`).join("")}
function openSubject(id){currentSubject=C.subjects.find(s=>s.id===id);$("#home").classList.add("hidden");$("#subjectView").classList.remove("hidden");$("#subjectTitle").innerHTML=`${currentSubject.icon} ${currentSubject.title} <span class="ar">• ${currentSubject.ar}</span>`;$("#standards").textContent=currentSubject.standards.join(" • ");$("#lessonList").innerHTML=currentSubject.lessons.map((l,i)=>`<button class="lessonCard" data-id="${l.id}"><span class="icon">${["👀","🎧","🎮","🧠"][i%4]}</span><b>${l.title}</b><span class="ar">${l.ar}</span><small>${l.intro}</small></button>`).join("");$("#lessonList").querySelectorAll(".lessonCard").forEach(b=>b.onclick=()=>openLesson(b.dataset.id));scrollTo({top:0,behavior:"smooth"})}
function openLesson(id){currentLesson=currentSubject.lessons.find(l=>l.id===id);$("#subjectView").classList.add("hidden");$("#lessonView").classList.remove("hidden");$("#lessonTitle").innerHTML=`${currentSubject.icon} ${currentLesson.title} <span class="ar">• ${currentLesson.ar}</span>`;$("#lessonIntro").textContent=currentLesson.intro;$("#items").innerHTML=currentLesson.items.map((x,i)=>`<button class="item" data-i="${i}"><span>${x[0]}</span>${x[1]}<small>🔊 Tap to listen • اضغط للاستماع</small></button>`).join("");$("#items").querySelectorAll(".item").forEach(b=>b.onclick=()=>{const x=currentLesson.items[+b.dataset.i];speak(x[1],$("#voice").value);$("#feedback").textContent="🌟 Great listening! ممتاز — "+x[1]});renderMemory();renderQuiz();scrollTo({top:0,behavior:"smooth"})}
function renderMemory(){hiddenMemory=false;remembered=new Set();$("#memoryGrid").innerHTML=currentLesson.items.slice(0,4).map((x,i)=>`<button class="memoryCard" data-i="${i}"><span style="font-size:34px">${x[0]}</span><br><b>${x[1]}</b></button>`).join("");$("#memoryToggle").textContent="🙈 Hide & recall • أخفِ وتذكر";$("#memoryScore").textContent="Look, link the pictures in a funny story, then hide them."}
function toggleMemory(){hiddenMemory=!hiddenMemory;remembered=new Set();const cards=$$("#memoryGrid .memoryCard");cards.forEach((b,i)=>{const x=currentLesson.items[i];b.innerHTML=hiddenMemory?"❓<br><b>Do you remember?</b>":`<span style="font-size:34px">${x[0]}</span><br><b>${x[1]}</b>`;b.onclick=hiddenMemory?()=>remember(i,b):null});$("#memoryToggle").textContent=hiddenMemory?"👀 Show & review • راجع":"🙈 Hide & recall • أخفِ وتذكر";$("#memoryScore").textContent=hiddenMemory?"Tap each card you can recall before showing the answers.":"Review the pictures and key words again."}
function remember(i,b){if(remembered.has(i))return;remembered.add(i);b.classList.add("good");b.innerHTML="⭐<br><b>I remembered!</b>";$("#memoryScore").textContent=`Memory stars: ${remembered.size} / ${Math.min(4,currentLesson.items.length)}`}
function renderQuiz(){const q=currentLesson.quiz;$("#quizQ").textContent=q.q;$("#answers").innerHTML=q.choices.map((c,i)=>`<button data-i="${i}">${String.fromCharCode(65+i)}. ${c}</button>`).join("");$("#quizFeedback").textContent="";$("#answers").querySelectorAll("button").forEach(b=>b.onclick=()=>{const i=+b.dataset.i;$("#answers").querySelectorAll("button").forEach(x=>x.disabled=true);if(i===q.answer){b.classList.add("good");$("#quizFeedback").textContent="🌟 Excellent! ممتاز — correct answer."}else{b.classList.add("try");$("#answers").children[q.answer].classList.add("good");$("#quizFeedback").textContent="🌱 Good try! محاولة جيدة — review and try again."}})}
function backHome(){$("#subjectView").classList.add("hidden");$("#lessonView").classList.add("hidden");$("#home").classList.remove("hidden");scrollTo({top:0,behavior:"smooth"})}
function backSubject(){$("#lessonView").classList.add("hidden");$("#subjectView").classList.remove("hidden");scrollTo({top:0,behavior:"smooth"})}
document.addEventListener("DOMContentLoaded",()=>{renderSubjects();$("#memoryToggle").onclick=toggleMemory;$("#homeBtn").onclick=backHome;$("#subjectBack").onclick=backHome;$("#lessonBack").onclick=backSubject;$("#girlVoice").onclick=()=>{ $("#voice").value="girl";speak("Hello! Let us learn together!","girl")};$("#boyVoice").onclick=()=>{ $("#voice").value="boy";speak("Hello! Let us learn and play!","boy")};if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js")});